
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package pacotePrincipal;

/** CUP generated interface containing symbol constants. */
public interface AnalisadorSintaticoSym {
  /* terminals */
  public static final int CHAR = 9;
  public static final int DIVIDED = 34;
  public static final int INTEGER = 6;
  public static final int GREATER = 31;
  public static final int EOLCHAR = 21;
  public static final int LESS = 30;
  public static final int WRITE = 19;
  public static final int AND = 39;
  public static final int NOT = 28;
  public static final int GRATEREQUAL = 36;
  public static final int LESSEQUAL = 35;
  public static final int OR = 38;
  public static final int BEGIN = 10;
  public static final int MULOP = 4;
  public static final int UNTIL = 17;
  public static final int DIFFERENT = 37;
  public static final int PLUS = 32;
  public static final int IF = 12;
  public static final int RELOP = 3;
  public static final int ENUMCHAR = 23;
  public static final int EOF = 0;
  public static final int BOOLEAN = 8;
  public static final int EQUAL = 29;
  public static final int error = 1;
  public static final int PROGRAM = 5;
  public static final int DECCHAR = 22;
  public static final int MOD = 40;
  public static final int ADDOP = 2;
  public static final int REAL = 7;
  public static final int TIMES = 33;
  public static final int ELSE = 14;
  public static final int READ = 18;
  public static final int WHILE = 16;
  public static final int THEN = 13;
  public static final int END = 11;
  public static final int CLOSEPARCHAR = 26;
  public static final int ASSIGNCHAR = 24;
  public static final int MINUSCHAR = 27;
  public static final int DO = 15;
  public static final int OPENPARCHAR = 25;
  public static final int IDENTIFIER = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ADDOP",
  "RELOP",
  "MULOP",
  "PROGRAM",
  "INTEGER",
  "REAL",
  "BOOLEAN",
  "CHAR",
  "BEGIN",
  "END",
  "IF",
  "THEN",
  "ELSE",
  "DO",
  "WHILE",
  "UNTIL",
  "READ",
  "WRITE",
  "IDENTIFIER",
  "EOLCHAR",
  "DECCHAR",
  "ENUMCHAR",
  "ASSIGNCHAR",
  "OPENPARCHAR",
  "CLOSEPARCHAR",
  "MINUSCHAR",
  "NOT",
  "EQUAL",
  "LESS",
  "GREATER",
  "PLUS",
  "TIMES",
  "DIVIDED",
  "LESSEQUAL",
  "GRATEREQUAL",
  "DIFFERENT",
  "OR",
  "AND",
  "MOD"
  };
}

