/* The following code was generated by JFlex 1.7.0 */

package pacotePrincipal;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>C:/Users/dougl/eclipse-workspace/Compilador/src/pacoteLexico/Yylex.lex</tt>
 */
class AnalisadorLexico {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  3,  2,  0,  3,  1,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     3, 19,  0,  0,  0,  0,  0,  8, 34, 34, 22,  6,  0,  6,  0, 22, 
     5,  5,  5,  5,  5,  5,  5,  5,  5,  5, 33, 34, 18, 17, 18,  0, 
     0,  4,  4,  4,  4,  7,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4, 
     4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  0,  0,  0,  0,  0, 
     0, 10, 29, 30, 23, 13,  9, 28, 31, 24,  4,  4, 11, 26, 20, 21, 
    27,  4, 15, 12, 14, 16, 25, 32,  4,  4,  4,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\0\6\2\2\5"+
    "\1\0\2\2\1\6\7\2\2\7\2\3\1\0\11\2"+
    "\1\4\1\10\1\2\1\11\7\2\2\0\1\12\1\2"+
    "\1\6\1\2\1\13\4\2\1\5\7\2\1\3\1\14"+
    "\1\3\1\15\1\16\1\17\5\2\1\20\2\2\1\21"+
    "\2\2\1\22\1\2\1\23\1\24\3\2\1\25\1\26"+
    "\1\27";

  private static int [] zzUnpackAction() {
    int [] result = new int[96];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\43\0\106\0\151\0\214\0\257\0\322\0\365"+
    "\0\u0118\0\u013b\0\u015e\0\u0181\0\214\0\u01a4\0\u01a4\0\u01c7"+
    "\0\u01ea\0\214\0\u020d\0\u0230\0\u0253\0\u0276\0\u0299\0\u02bc"+
    "\0\u02df\0\u0302\0\214\0\u0325\0\u0348\0\u036b\0\u038e\0\u03b1"+
    "\0\u03d4\0\u03f7\0\u041a\0\u043d\0\u0460\0\u0483\0\u04a6\0\106"+
    "\0\106\0\u04c9\0\106\0\u04ec\0\u050f\0\u0532\0\u0555\0\u0578"+
    "\0\u059b\0\u05be\0\u05e1\0\u0604\0\214\0\u0627\0\106\0\u064a"+
    "\0\106\0\u066d\0\u0690\0\u06b3\0\u06d6\0\106\0\u06f9\0\u071c"+
    "\0\u073f\0\u0762\0\u0785\0\u07a8\0\u07cb\0\u0604\0\106\0\106"+
    "\0\106\0\106\0\106\0\u07ee\0\u0811\0\u0834\0\u0857\0\u087a"+
    "\0\106\0\u089d\0\u08c0\0\106\0\u08e3\0\u0906\0\106\0\u0929"+
    "\0\106\0\106\0\u094c\0\u096f\0\u0992\0\106\0\106\0\106";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[96];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\3\2\1\3\1\4\1\5\1\3\1\6\1\7"+
    "\1\10\2\3\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\3\1\25"+
    "\1\26\1\3\1\27\1\30\1\3\1\31\1\32\1\33"+
    "\1\0\3\2\43\0\2\3\1\0\1\3\1\0\10\3"+
    "\3\0\2\3\1\0\12\3\2\0\2\34\1\0\2\34"+
    "\1\4\1\34\1\35\33\34\43\0\1\36\2\0\40\36"+
    "\4\0\2\3\1\0\1\3\1\0\1\3\1\37\6\3"+
    "\3\0\2\3\1\0\12\3\6\0\2\3\1\0\1\3"+
    "\1\0\10\3\3\0\1\40\1\3\1\0\12\3\6\0"+
    "\2\3\1\0\1\3\1\0\2\3\1\41\5\3\3\0"+
    "\1\42\1\3\1\0\12\3\6\0\2\3\1\0\1\3"+
    "\1\0\6\3\1\43\1\3\3\0\2\3\1\0\10\3"+
    "\1\44\1\3\6\0\2\3\1\0\1\3\1\0\4\3"+
    "\1\45\3\3\3\0\2\3\1\0\12\3\6\0\2\3"+
    "\1\0\1\3\1\0\10\3\3\0\1\46\1\3\1\0"+
    "\12\3\23\0\1\15\25\0\2\3\1\0\1\3\1\0"+
    "\10\3\3\0\1\3\1\47\1\0\12\3\6\0\2\3"+
    "\1\0\1\3\1\0\6\3\1\50\1\3\3\0\2\3"+
    "\1\0\12\3\6\0\2\3\1\0\1\3\1\0\10\3"+
    "\3\0\1\3\1\51\1\0\1\3\1\52\10\3\6\0"+
    "\2\3\1\0\1\3\1\0\1\53\7\3\3\0\1\54"+
    "\1\3\1\0\12\3\6\0\2\3\1\0\1\3\1\0"+
    "\10\3\3\0\1\3\1\40\1\0\12\3\6\0\2\3"+
    "\1\0\1\3\1\0\6\3\1\55\1\3\3\0\2\3"+
    "\1\0\12\3\6\0\2\3\1\0\1\3\1\0\4\3"+
    "\1\56\3\3\3\0\1\3\1\57\1\0\12\3\6\0"+
    "\2\3\1\0\1\3\1\0\10\3\3\0\2\3\1\0"+
    "\10\3\1\60\1\3\6\0\2\3\1\0\1\3\1\0"+
    "\6\3\1\61\1\3\3\0\2\3\1\0\10\3\1\62"+
    "\1\3\23\0\1\33\26\0\1\34\1\0\1\63\40\0"+
    "\1\34\1\64\1\63\43\0\1\65\36\0\2\3\1\0"+
    "\1\3\1\0\2\3\1\66\5\3\3\0\2\3\1\0"+
    "\12\3\6\0\2\3\1\0\1\3\1\0\10\3\3\0"+
    "\2\3\1\0\1\67\11\3\6\0\2\3\1\0\1\3"+
    "\1\0\3\3\1\70\4\3\3\0\2\3\1\0\12\3"+
    "\6\0\2\3\1\0\1\3\1\0\10\3\3\0\2\3"+
    "\1\0\1\71\11\3\6\0\2\3\1\0\1\3\1\0"+
    "\7\3\1\72\3\0\2\3\1\0\12\3\6\0\2\3"+
    "\1\0\1\3\1\0\4\3\1\73\3\3\3\0\2\3"+
    "\1\0\12\3\6\0\2\3\1\0\1\3\1\0\1\3"+
    "\1\74\6\3\3\0\2\3\1\0\12\3\6\0\2\3"+
    "\1\0\1\3\1\0\5\3\1\75\2\3\3\0\2\3"+
    "\1\0\12\3\6\0\2\3\1\0\1\3\1\0\5\3"+
    "\1\76\2\3\3\0\2\3\1\0\12\3\6\0\2\3"+
    "\1\0\1\3\1\0\10\3\3\0\2\3\1\0\2\3"+
    "\1\67\7\3\6\0\2\3\1\0\1\3\1\0\5\3"+
    "\1\77\2\3\3\0\2\3\1\0\12\3\6\0\2\3"+
    "\1\0\1\3\1\0\10\3\3\0\1\3\1\100\1\0"+
    "\12\3\6\0\2\3\1\0\1\3\1\0\10\3\3\0"+
    "\2\3\1\0\5\3\1\101\4\3\6\0\2\3\1\0"+
    "\1\3\1\0\10\3\3\0\1\3\1\102\1\0\12\3"+
    "\6\0\2\3\1\0\1\3\1\0\1\3\1\103\6\3"+
    "\3\0\2\3\1\0\12\3\6\0\2\3\1\0\1\3"+
    "\1\0\10\3\3\0\2\3\1\0\1\3\1\104\10\3"+
    "\6\0\2\3\1\0\1\3\1\0\10\3\3\0\2\3"+
    "\1\0\1\3\1\105\10\3\7\0\1\106\1\64\41\0"+
    "\1\106\41\0\2\3\1\0\1\3\1\0\3\3\1\72"+
    "\4\3\3\0\2\3\1\0\12\3\6\0\2\3\1\0"+
    "\1\3\1\0\4\3\1\107\3\3\3\0\2\3\1\0"+
    "\12\3\6\0\2\3\1\0\1\3\1\0\4\3\1\110"+
    "\3\3\3\0\2\3\1\0\12\3\6\0\2\3\1\0"+
    "\1\3\1\0\10\3\3\0\1\111\1\3\1\0\12\3"+
    "\6\0\2\3\1\0\1\3\1\0\2\3\1\112\5\3"+
    "\3\0\2\3\1\0\1\113\11\3\6\0\2\3\1\0"+
    "\1\3\1\0\10\3\3\0\2\3\1\0\1\3\1\114"+
    "\10\3\6\0\2\3\1\0\1\3\1\0\4\3\1\115"+
    "\3\3\3\0\2\3\1\0\12\3\6\0\2\3\1\0"+
    "\1\3\1\0\10\3\3\0\2\3\1\0\5\3\1\116"+
    "\4\3\6\0\2\3\1\0\1\3\1\0\10\3\3\0"+
    "\2\3\1\0\1\3\1\117\10\3\6\0\2\3\1\0"+
    "\1\3\1\0\2\3\1\120\5\3\3\0\2\3\1\0"+
    "\12\3\6\0\2\3\1\0\1\3\1\0\6\3\1\121"+
    "\1\3\3\0\2\3\1\0\12\3\6\0\2\3\1\0"+
    "\1\3\1\0\5\3\1\122\2\3\3\0\2\3\1\0"+
    "\12\3\6\0\2\3\1\0\1\3\1\0\2\3\1\123"+
    "\5\3\3\0\2\3\1\0\12\3\6\0\2\3\1\0"+
    "\1\3\1\0\2\3\1\124\5\3\3\0\2\3\1\0"+
    "\12\3\6\0\2\3\1\0\1\3\1\0\10\3\3\0"+
    "\2\3\1\0\5\3\1\125\4\3\6\0\2\3\1\0"+
    "\1\3\1\0\6\3\1\126\1\3\3\0\2\3\1\0"+
    "\12\3\6\0\2\3\1\0\1\3\1\0\10\3\3\0"+
    "\1\127\1\3\1\0\12\3\6\0\2\3\1\0\1\3"+
    "\1\0\4\3\1\130\3\3\3\0\2\3\1\0\12\3"+
    "\6\0\2\3\1\0\1\3\1\0\4\3\1\131\3\3"+
    "\3\0\2\3\1\0\12\3\6\0\2\3\1\0\1\3"+
    "\1\0\4\3\1\132\3\3\3\0\2\3\1\0\12\3"+
    "\6\0\2\3\1\0\1\3\1\0\4\3\1\133\3\3"+
    "\3\0\2\3\1\0\12\3\6\0\2\3\1\0\1\3"+
    "\1\0\1\3\1\134\6\3\3\0\2\3\1\0\12\3"+
    "\6\0\2\3\1\0\1\3\1\0\1\3\1\135\6\3"+
    "\3\0\2\3\1\0\12\3\6\0\2\3\1\0\1\3"+
    "\1\0\6\3\1\136\1\3\3\0\2\3\1\0\12\3"+
    "\6\0\2\3\1\0\1\3\1\0\10\3\3\0\2\3"+
    "\1\0\3\3\1\137\6\3\6\0\2\3\1\0\1\3"+
    "\1\0\10\3\3\0\1\140\1\3\1\0\12\3\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2485];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\3\1\1\11\1\0\6\1\1\11\1\1\1\0"+
    "\2\1\1\11\10\1\1\11\2\1\1\0\24\1\2\0"+
    "\1\11\53\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[96];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */

private void imprimir(String tipo, String valor) {
    System.out.println("(" + tipo + ", " + valor + ")");
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  AnalisadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public void yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                System.exit(0);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { /* ignora */
            } 
            // fall through
          case 24: break;
          case 2: 
            { imprimir("identifier", yytext());
            } 
            // fall through
          case 25: break;
          case 3: 
            { imprimir("constant", yytext());
            } 
            // fall through
          case 26: break;
          case 4: 
            { imprimir("ADDOP", yytext());
            } 
            // fall through
          case 27: break;
          case 5: 
            { imprimir("RELOP", yytext());
            } 
            // fall through
          case 28: break;
          case 6: 
            { imprimir("MULOP", yytext());
            } 
            // fall through
          case 29: break;
          case 7: 
            { 
            } 
            // fall through
          case 30: break;
          case 8: 
            { imprimir("do", "");
            } 
            // fall through
          case 31: break;
          case 9: 
            { imprimir("if", "");
            } 
            // fall through
          case 32: break;
          case 10: 
            { imprimir("constant", yytext().substring(1, 2));
            } 
            // fall through
          case 33: break;
          case 11: 
            { imprimir("end", "");
            } 
            // fall through
          case 34: break;
          case 12: 
            { imprimir("else", "");
            } 
            // fall through
          case 35: break;
          case 13: 
            { imprimir("then", "");
            } 
            // fall through
          case 36: break;
          case 14: 
            { imprimir("real", "");
            } 
            // fall through
          case 37: break;
          case 15: 
            { imprimir("read", "");
            } 
            // fall through
          case 38: break;
          case 16: 
            { imprimir("char", "");
            } 
            // fall through
          case 39: break;
          case 17: 
            { imprimir("until", "");
            } 
            // fall through
          case 40: break;
          case 18: 
            { imprimir("begin", "");
            } 
            // fall through
          case 41: break;
          case 19: 
            { imprimir("write", "");
            } 
            // fall through
          case 42: break;
          case 20: 
            { imprimir("while", "");
            } 
            // fall through
          case 43: break;
          case 21: 
            { imprimir("integer", "");
            } 
            // fall through
          case 44: break;
          case 22: 
            { imprimir("program", "");
            } 
            // fall through
          case 45: break;
          case 23: 
            { imprimir("boolean", "");
            } 
            // fall through
          case 46: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
